### PR TITLE
[CodeWhisperer] add JSX enum type in CodeWhispererProgrammingLanguage

### PR DESCRIPTION
**Pull request by Will-ShaoHua**
As title, CodeWhisperer team aims to support JSX files, add a new programmingLanguage type for us to track JSX use cases.

## Checklist

- [ ] I have read the **README** document
- [ ] I have read the **CONTRIBUTING** document
- [ ] My code follows the code style of this project
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License
I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
This is still in draft, is that intentional?

**Comment by Will-ShaoHua** [comment]
hihi Justin, yes it's intentional since it's still under discussion if we need to add this field. Should I close this for now and reopen later if needed?

**Comment by Will-ShaoHua** [comment]
yea @justinmk3 , since we still have discussion over the `enabled` field for codewhisperer_percentage metrics.
And sorry for the churn, I accidentally hard push and override this PR to be JSX one. Will open another for the original one once our team align on that field. Thanks!

**Review by zixlin7 — APPROVED** [review]

**Review by andrewyuq — APPROVED** [review]
hmm it should use a separate PR but ok

**Comment by Will-ShaoHua** [comment]
> hmm it should use a separate PR but ok

yea, i forgot I do have a PR on this branch and I force-pushed it... so here i am

**Review by justinmk3 — APPROVED** [review]

**Pull request merged**
