### PR TITLE
telemetry: cwsprChatUserIntent

### PR DESCRIPTION
**Pull request by lalexcaws**
## Problem
Plugins telemetry data should now include the user intent as part of message interaction

## Solution
Modify common definition to include user intent

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by justinmk3** [comment]
CI is failing

do you also plan to remove the toolkit-local definition here: https://github.com/aws/aws-toolkit-vscode/blob/1db0f973b1db2011cc442b5c78e7fac186cd1d4e/packages/core/src/shared/telemetry/vscodeTelemetry.json#L811 (it should be upstreamed/synced with this common definition)

**Comment by lalexcaws** [comment]
> CI is failing
> 
> do you also plan to remove the toolkit-local definition here: https://github.com/aws/aws-toolkit-vscode/blob/1db0f973b1db2011cc442b5c78e7fac186cd1d4e/packages/core/src/shared/telemetry/vscodeTelemetry.json#L811 (it should be upstreamed/synced with this common definition)

Yeah, I can remove the local definition once this common definition is done

**Comment by hayemaxi** [comment]
> > CI is failing
> > do you also plan to remove the toolkit-local definition here: https://github.com/aws/aws-toolkit-vscode/blob/1db0f973b1db2011cc442b5c78e7fac186cd1d4e/packages/core/src/shared/telemetry/vscodeTelemetry.json#L811 (it should be upstreamed/synced with this common definition)
> 
> Yeah, I can remove the local definition once this common definition is done

Please make an internal ticket to ensure this is tracked.

**Review by hayemaxi — APPROVED** [review]

**Comment by hayemaxi** [comment]
Thank you for porting this quickly!

**Pull request merged**
